services:
  web:
    platform: linux/amd64
    build: .
    env_file: .env
    ports:
      - "8181:80"
    volumes:
      - web_assets:/var/www/html/assets/images
      - web_storage:/var/www/html/core/storage/app
    depends_on:
      - db

  db:
    image: mariadb:10.6
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql

volumes:
  web_assets:
  web_storage:

